import { v } from "convex/values";
import { convex } from "./builder";
import { consumeRateLimit, hashMikebotToken } from "./mikebot/guards";

/**
 * Registers the anonymous Mikebot identity for a secret token generated by the
 * visitor's browser. Idempotent: calling it again with the same token is a no-op.
 * Only the SHA-256 hash of the token is stored.
 */
export const ensureAnonymousUser = convex
  .mutation()
  .input({ token: v.string() })
  .returns(v.null())
  .handler(async (ctx, { token }) => {
    const tokenHash = hashMikebotToken(token);

    const existing = await ctx.db
      .query("users")
      .withIndex("by_tokenHash", (q) => q.eq("tokenHash", tokenHash))
      .unique();
    if (existing) return null;

    await consumeRateLimit(ctx, "createAnonymousUserGlobal");
    await ctx.db.insert("users", { kind: "anonymous", tokenHash });
    return null;
  })
  .public();
